name: Large Dataset Datacap Application
description: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "[DataCap Application] <Organization> - <Project Name>"
labels: 'LDN'
body:
- type: markdown
  attributes:
    value: |
      # Large Dataset Notary Application - Version 1
      To apply for DataCap to onboard your dataset to Filecoin, please fill out the following form
- type: markdown
  attributes:
    value: |
      # Application Info
- type: dropdown
  id: version
  attributes:
      label: Version
      description: Schema File Version
      options:
        - 1
  validations:
    required: true
- type: input
  attributes:
    label: On Chain Address
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Client Info
- type: input
  attributes:
    label: Name
  validations:
    required: true
- type: dropdown
  attributes:
    label: Region
    options:
      - Afghanistan
      - Åland Islands
      - Albania
      - Algeria
      - American Samoa
      - Andorra
      - Angola
      - Anguilla
      - Antarctica
      - Antigua and Barbuda
      - Argentina
      - Armenia
      - Aruba
      - Australia
      - Austria
      - Azerbaijan
      - Bahamas
      - Bahrain
      - Bangladesh
      - Barbados
      - Belarus
      - Belgium
      - Belize
      - Benin
      - Bermuda
      - Bhutan
      - Bolivia
      - "Bonaire, Sint Eustatius and Saba"
      - Bosnia and Herzegovina
      - Botswana
      - Bouvet Island
      - Brazil
      - British Indian Ocean Territory
      - Brunei Darussalam
      - Bulgaria
      - Burkina Faso
      - Burundi
      - Cambodia
      - Cameroon
      - Canada
      - Cape Verde
      - Cayman Islands
      - Central African Republic
      - Chad
      - Chile
      - China
      - Christmas Island
      - Cocos (Keeling) Islands
      - Colombia
      - Comoros
      - Congo
      - "Congo, the Democratic Republic of the"
      - Cook Islands
      - Costa Rica
      - Côte d'Ivoire
      - Croatia
      - Cuba
      - Curaçao
      - Cyprus
      - Czech Republic
      - Denmark
      - Djibouti
      - Dominica
      - Dominican Republic
      - Ecuador
      - Egypt
      - El Salvador
      - Equatorial Guinea
      - Eritrea
      - Estonia
      - Ethiopia
      - Falkland Islands (Malvinas)
      - Faroe Islands
      - Fiji
      - Finland
      - France
      - French Guiana
      - French Polynesia
      - French Southern Territories
      - Gabon
      - Gambia
      - Georgia
      - Germany
      - Ghana
      - Gibraltar
      - Greece
      - Greenland
      - Grenada
      - Guadeloupe
      - Guam
      - Guatemala
      - Guernsey
      - Guinea
      - Guinea-Bissau
      - Guyana
      - Haiti
      - Heard Island and McDonald Islands
      - Holy See (Vatican City State)
      - Honduras
      - Hong Kong
      - Hungary
      - Iceland
      - India
      - Indonesia
      - "Iran, Islamic Republic of"
      - Iraq
      - Ireland
      - Isle of Man
      - Israel
      - Italy
      - Jamaica
      - Japan
      - Jersey
      - Jordan
      - Kazakhstan
      - Kenya
      - Kiribati
      - "Korea, Democratic People's Republic of"
      - "Korea, Republic of"
      - Kuwait
      - Kyrgyzstan
      - Lao People's Democratic Republic
      - Latvia
      - Lebanon
      - Lesotho
      - Liberia
      - Libya
      - Liechtenstein
      - Lithuania
      - Luxembourg
      - Macao
      - "Macedonia, the Former Yugoslav Republic of"
      - Madagascar
      - Malawi
      - Malaysia
      - Maldives
      - Mali
      - Malta
      - Marshall Islands
      - Martinique
      - Mauritania
      - Mauritius
      - Mayotte
      - Mexico
      - "Micronesia, Federated States of"
      - "Moldova, Republic of"
      - Monaco
      - Mongolia
      - Montenegro
      - Montserrat
      - Morocco
      - Mozambique
      - Myanmar
      - Namibia
      - Nauru
      - Nepal
      - Netherlands
      - New Caledonia
      - New Zealand
      - Nicaragua
      - Niger
      - Nigeria
      - Niue
      - Norfolk Island
      - Northern Mariana Islands
      - Norway
      - Oman
      - Pakistan
      - Palau
      - "Palestine, State of"
      - Panama
      - Papua New Guinea
      - Paraguay
      - Peru
      - Philippines
      - Pitcairn
      - Poland
      - Portugal
      - Puerto Rico
      - Qatar
      - Réunion
      - Romania
      - Russian Federation
      - Rwanda
      - Saint Barthélemy
      - "Saint Helena, Ascension and Tristan da Cunha"
      - Saint Kitts and Nevis
      - Saint Lucia
      - Saint Martin (French part)
      - Saint Pierre and Miquelon
      - Saint Vincent and the Grenadines
      - Samoa
      - San Marino
      - Sao Tome and Principe
      - Saudi Arabia
      - Senegal
      - Serbia
      - Seychelles
      - Sierra Leone
      - Singapore
      - Sint Maarten (Dutch part)
      - Slovakia
      - Slovenia
      - Solomon Islands
      - Somalia
      - South Africa
      - South Georgia and the South Sandwich Islands
      - South Sudan
      - Spain
      - Sri Lanka
      - Sudan
      - Suriname
      - Svalbard and Jan Mayen
      - Swaziland
      - Sweden
      - Switzerland
      - Syrian Arab Republic
      - Taiwan
      - Tajikistan
      - "Tanzania, United Republic of"
      - Thailand
      - Timor-Leste
      - Togo
      - Tokelau
      - Tonga
      - Trinidad and Tobago
      - Tunisia
      - Turkey
      - Turkmenistan
      - Turks and Caicos Islands
      - Tuvalu
      - Uganda
      - Ukraine
      - United Arab Emirates
      - United Kingdom
      - United States
      - United States Minor Outlying Islands
      - Uruguay
      - Uzbekistan
      - Vanuatu
      - "Venezuela, Bolivarian Republic of"
      - Viet Nam
      - "Virgin Islands, British"
      - "Virgin Islands, U.S."
      - Wallis and Futuna
      - Western Sahara
      - Yemen
      - Zambia
      - Zimbabwe
  validations:
    required: true
- type: input
  attributes:
    label: Industry
  validations:
    required: true
- type: input
  attributes:
    label: Website
  validations:
    required: true
- type: input
  attributes:
    label: Social Media
  validations:
    required: true
- type: input
  attributes:
    label: Role
  validations:
    required: true
