name: ProposalValidator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install fplus-cli
      run: echo 'Install fplus-cli'
      # run: cargo install fplus-cli && fplus-cli app_id
    - name: Validate Proposal
      run: echo 'Validate Proposal'  
      # run: fplus-clia app_id

