name: Validate triggering application

on:
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_review:
    types:
      - submitted

jobs:
  call-backend:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
      - name: Call Backend with PR Number and User Handle
        run: |
          echo "Validating triggering application from pr number ${{ github.event.pull_request.number }} and user handle ${{ github.actor }}"
          curl --header "Content-Type: application/json" \
              --request POST \
              --data '{"pr_number": "'${{ github.event.pull_request.number }}'", "user_handle": "'${{ github.actor }}'"}' \
              "${DOMAIN}/application/trigger/validate"