name: TriggerValidator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install fplus-cli
      run: echo 'Install fplus-cli'
      # run: cargo install fplus-cli
    - name: Validate Trigger
      run: echo 'Validate Trigger'  
      # run: fplus-cli validate-trigger app_id


