name: Validate triggering application

on:
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_review:
    types:
      - submitted

jobs:
  call-backend:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
      - name: Call Backend to Validate
        id: validate
        run: |
          BODY=$(curl --silent --header "Content-Type: application/json" \
            --request POST \
            --data '{"pr_number": "'${{ github.event.pull_request.number }}'", "user_handle": "'${{ github.actor }}'"}' \
            "${DOMAIN}/application/trigger/validate")

          # Check if the body of the response is true
          if [ "$BODY" != "true" ]; then
            echo "Error: Validation returned false"
            exit 1
          fi

      - name: Validation Success
        if: steps.validate.outcome == 'success'
        run: echo "Validation successful!"